("huevo frito")
print("preparar un huevo frito")
print("tengo huevos disponibles")
huevosDisponibles = input().upper()
if huevosDisponibles == "NO":
    print("comprar huevos")
    print("buscar el aceite de cocina")
else:
    print("buscar aceite de cocina")
    ingredientes = input()
print("tengo aceite disponible")
aceiteDisponible = input().upper()
if aceiteDisponible == "NO":
    print("comprar aceite de cocina")
    print("colocar el sarten en la estufa")
else:
    print("colocar el sarten en la estufa")
    sarten = input()
print("encender el fogon")
fogon = input().upper()
print("agregar aceite al sarten")
agregarAceite = input().upper()
print("esperar que el aceite se caliente por 2 minutos")
esperar = input().upper()
print("romper el huevo")
romper = input().upper()
print("colocar el huevo en el sarten")
colocarHuevo = input().upper()
print("esperar que el huevo este frito")
esperarHuevo = input().upper()
print("apagar fogon")
apagar = input().upper()
print("retirar el huevo del sarten")
retirar = input().upper()
print("poner el huevo en un plato")
plato = input().upper()